import { Inter, Poppins } from "next/font/google";
import ".././globals.css";
import { Provider } from "@/app/providers";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import UserHeader from "@/components/UserHeader/UserHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "greek"],
});

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const locale = (await params).locale;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  const fontClass = locale === "el" ? inter.className : poppins.className;

  return (
    <html lang={locale}>
      <body className={`antialiased ${fontClass}`}>
        <Provider>
          <NextIntlClientProvider messages={messages}>
            <header className=" relative z-30">
              <UserHeader />
            </header>
            {children}
            {/* <footer>
              <Footer />
            </footer> */}
          </NextIntlClientProvider>
        </Provider>
      </body>
    </html>
  );
}
